version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
      - AUTH_SECRET=${{ secrets.AUTH_SECRET }}
      - AZURE_AD_TENANT_ID=${{ secrets.AZURE_AD_TENANT_ID }}
      - AZURE_AD_CLIENT_SECRET=${{ secrets.AZURE_AD_CLIENT_SECRET }}
      - AZURE_AD_CLIENT_ID=${{ secrets.AZURE_AD_CLIENT_ID }}
      - NEXTAUTH_URL=${{ secrets.NEXTAUTH_URL }}
      - NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }}
