# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - vercelaigafrontend

on:
  push:
    branches:
      - azuredeployment
  workflow_dispatch:
  
          
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:

      - name: Checkout
        uses: actions/checkout@v4
      
      - uses: pnpm/action-setup@0609f0983b7a228f052f81ef4c3d6510cae254ad
        with:
          version: 8

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'pnpm'

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Cache .next build and pnpm modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.pnpm-store
            ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.yaml') }}-

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
        
      - name: pnpm install, and build
        run: | 
          pnpm install --no-frozen-lockfile
          pnpm run build
          ls -la
      
      - name: Prepare deployment package
        run: |
          echo "Listing all files from .next/ to create zip:"
          zip -r release.zip .next node_modules package.json pnpm-lock.yaml

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3.1.3
        with:
          name: node-app
          path: ./release.zip

  deploy:
    runs-on: ubuntu-latest
    
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    permissions:
      contents: write
      packages: write
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2.1.1
        with:
          name: node-app
      - name: Display structure of downloaded files
        run: ls -R

      - name: 'Echo download path'
        run: echo ${{steps.download.outputs.download-path}}

      - name: unzip artifact for deployment
        run: |
          unzip release.zip
          rm -rf release.zip
          pwd
          ls -la

      - name: 'Deploy to Azure WebApp'
        id: deploy-to-webapp 
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'vercelaigafrontend'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_04003FDCA94B4BE3928B4850814F6E61 }}
          package: .
