# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - vercelaigafrontend

on:
  push:
    branches:
      - azuredeployment
  workflow_dispatch:
  
          
jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v2
            
      - name: Cache pnpm
        uses: actions/cache@v2
        with:
          path: ${{ env.pnpm_config_cache }}
          key: pnpm-${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}
          displayName: Cache pnpm
  
      - name: Cache .next/cache
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/.next/cache
          key: next-${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}
          displayName: "Cache .next/cache"
  
      - name: Setup pnpm
        run: |
          curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm@7
          pnpm config set store-dir ${{ env.pnpm_config_cache }}
          displayName: "Setup pnpm"
  
      - name: Install and build
        run: |
          pnpm install
          pnpm run build
          displayName: "pnpm install and build"
      - uses: actions/checkout@v3
          
      - name: Set up Node.js version
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
              
      - name: Install sudo
        run: |
          sudo apt-get update
          sudo apt-get install -y sudo
          
      - name: npm install, build, and test
        run: | 
          npm install -g pnpm
          pnpm install --no-frozen-lockfile
          pnpm run build
      
      - name: Zip artifact for deployment
        run: zip -r release.zip . -i ./build/*
      
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: node-app
          path: ./release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: node-app

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'vercelaigafrontend'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_04003FDCA94B4BE3928B4850814F6E61 }}
          package: .
