# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - vercelaigafrontend

on:
  push:
    branches:
      - azuredeployment
  workflow_dispatch:
  
          
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
          
      - name: Set up Node.js version
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'
              
      - name: Install sudo
        run: |
          sudo apt-get update
          sudo apt-get install -y sudo
          
      - name: npm install, build, and test
        run: | 
          npm install -g pnpm
          pnpm install --no-frozen-lockfile
          pnpm run build
      
      - name: Zip artifact for deployment
        run: zip -r release.zip . -i ./build/*
      
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: node-app
          path: ./release.zip

      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Cache pnpm
        uses: actions/cache@v2
        with:
          key: 'pnpm | "${{ runner.os }}" | pnpm-lock.yaml'
          path: ${{ runner.workspace }}/.pnpm-store

      - name: Cache .next/cache
        uses: actions/cache@v2
        with:
          key: next | ${{ runner.os }} | pnpm-lock.yaml
          path: ${{ github.workspace }}/.next/cache

      - name: Setup pnpm
        run: |
          curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm@7
          pnpm config set store-dir ${{ runner.workspace }}/.pnpm-store

      - name: Install and build
        run: |
          pnpm install --no-frozen-lockfile
          pnpm run build

      - name: Archive files
        run: zip -r release.zip . -i ./build/*
      
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: node-app
          path: ./release.zip


  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    
    steps:
    - uses: actions/checkout@v3
    - name: Install pnpm
      uses: pnpm/action-setup@v2.2.1
      with:
        version: "8.x"
    - uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        registry-url: 'https://registry.npmjs.org/'
        cache: 'pnpm'
    - run: pnpm install
    - name: 'Deploy to Azure Web App'
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'vercelaigafrontend'
        slot-name: 'Production'
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_04003FDCA94B4BE3928B4850814F6E61 }}
        package: .
